### PR TITLE
Semester End Refactor & Documentation

### LINKED ISSUE #6: Semester-End Wrap Up: Document & Organize Code
Making a request here to organize code and add README's or update the Wiki.
We've already talked about this in-person, just making a note here for documentation.

**Documentation Needs:**
* How to start robot
* How to start swing code
* Which files give what capability
* Are there different versions shown in different files?

Thanks!

### PR DESCRIPTION
**Pull request by acbuynak**
This PR works to refactor and document the code developed by the 2021-2022 'Robotic Golf Simulator' capstone project.
Simulations were used to verify functionality was not lost during the refactor.

Closes #6

### CODE REVIEW

**Comment by acbuynak** [comment]
Noticed that the `Robot()` class which is used for kinematic calculations is near identicially duplicated across three files (listed in table below).
I'd propose this class get pulled out into its own file and imported when needed so overall code is simplified. The only difference I can find between the scripts is the following..

| script | differing line |
| ------- | ---------------- |
| `generate_CenterPoints.py` | `v5_0 = [0,self.links[4],0]` | 
|`swing_centerPointVariations.py` | `v5_0 = [self.links[4]*np.cos(np.pi/6),self.links[4]*np.cos(np.pi/12),self.links[4]*np.cos(np.pi/3)]` |
|`swing_superPoints_wfigures.py` | `v5_0 = [0,self.links[4],0]` | 


@cooper2563  Can you explain difference? There's no comments on the line the explain difference.
Can we move this all into a single file? Any clever solutions to account for the difference if intentional?

**Comment by cooper2563** [comment]
@acbuynak, the robot() class should be the same in all the files, so if you want to move this to its own place that is fine. This is a difference in the direction of the club sweet spot from the end of the club. The correct one is v5_0 = [0, self.links[4], 0]. This should be the convention for the robot() class.

**Comment by acbuynak** [comment]
> The correct one is v5_0 = [0, self.links[4], 0]. This should be the convention for the robot() class.

Made corrections and pushed 69c81ad4f371890a4a2a799d608057f9c8e670d3. Additionally, moved two other duplicated functions into a common file.

**Comment by acbuynak** [comment]
This PR is ready to merge. All scripts tested in latest Noetic build and are functional in simulation.

Will Squash Merge as there is no need to retain the commit history for this refactor, many of them are nonfunctional independently.

**Pull request merged**
